title: 开元阁
headline: 开元阁
theme: jekyll-theme-cayman
twitter_username: 杰基尔
github_username: 杰基尔
lang: "zh-CN"
description: 给大家看看
defaults:
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
      author: "Mr. Hyde"
      category: "project"
